### PR TITLE
 Recognise styled-components as React Components

### LINKED ISSUE #68: Doesn't work with styled-components
Hi there, thanks for this great library!

`styled-components` fails the `isReactComponent` test, which means it doesn't get rendered at all.

This is how a styled-component looks like:
screenshot 2018-11-30 15 30 04

I'll open a PR to address this soon. Cheers!

### PR DESCRIPTION
**Pull request by fsodano**
Currently styled-components are not being recognised as React components since they are an object wrapper around a React component.

The isReactComponent util function will now also look at the styledComponentId property since it's not present in the vue-styled-components implementation (so it won't mistakenly try to render a Vue styled-component as a React component).

Fixes #68

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,3 +1,6 @@
 /coverage
 /node_modules
 /yarn-error.log
+
+# IDEs
+/.idea
```
Comment (akxcv) [inline .gitignore]: This belongs to a [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

File: src/utils/isReactComponent.js [hunk 2]
```diff
@@ -1,14 +1,12 @@
 export default function isReactComponent (component) {
-  if (typeof component === 'object') {
+  if (typeof component === 'object' && component.styledComponentId === undefined) {
```
Comment (akxcv) [inline src/utils/isReactComponent.js]: This hack doesn't look good... Are you sure there's no better way to detect a styled component?

Also, if I'm not mistaken, React cannot render regular objects at all (if that hasn't been changed recently), so there should be another way.

File: tests/fixtures/StyledComponent.js [hunk 3]
```diff
@@ -0,0 +1,22 @@
+export default {
+  $$typeof: Symbol('react.forward_ref'),
```
Comment (akxcv) [inline tests/fixtures/StyledComponent.js]: What about checking this instead (check for ref forwarding)?

File: tests/fixtures/StyledComponent.js [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+  attrs: [],
+  componentStyle: {
+    rules: [
+      '\n  font-size: 20px;\n  line-height: 32px;\n  letter-spacing: .3;\n  margin: ',
```
Comment (akxcv) [inline tests/fixtures/StyledComponent.js]: Nitpicking here, but the `rules` section could be simplified (exact styles are not relevant to the test).

File: .gitignore (hunk 1 above)
Comment (fsodano) [reply .gitignore]: TIL. Thanks!

File: tests/fixtures/StyledComponent.js (hunk 3 above)
Comment (fsodano) [reply tests/fixtures/StyledComponent.js]: I can, and it'll work (that was my original implementation) it just looked more mysterious that looking for `styledComponentId`. I'll change it to check for ref forwarding.

File: tests/fixtures/StyledComponent.js (hunk 4 above)
Comment (fsodano) [reply tests/fixtures/StyledComponent.js]: Sure, I just copied and pasted a real-life example of what a styled-component object looks like. I'll simplify it.

File: tests/fixtures/StyledComponent.js (hunk 3 above)
Comment (akxcv) [reply tests/fixtures/StyledComponent.js]: Yeah, the problem with `styledComponentId` is that the implementation explicitly handles a case when a styled component is passed. But any other library that works similarly (but isn't `styled-components`) would fail to work. It's better to account for the most generic case.

**Comment by fsodano** [comment]
Thanks for the review @akxcv, please have another look when you can.

File: src/utils/isReactComponent.js [hunk 5]
```diff
@@ -1,14 +1,16 @@
...
     component.prototype.constructor.super.name.startsWith('Vue')
-  ) {
-    return false
-  } else {
-    return true
-  }
+  )
+}
+
+function isStyledComponent (component) {
```
Comment (akxcv) [inline src/utils/isReactComponent.js]: We're not checking for a styled component, we're checking for React ref forwarding. So this function should be named something like `isReactForwardedRef`.
